url: https://y7kim.github.io

# Site settings
title: Jay Kamat
email: jaygkamat@gmail.com
description: "Jay Kamat's portfolio website"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

- title: github
  url: http://github.com/jgkamat
- title: linux
  url: http://hub.docker.com/u/jgkamat/
- title: linkedin
  url: http://www.linkedin.com/in/jaykamat
- title: stack-overflow
  url: https://stackoverflow.com/users/4196467/jay-kamat
- title: code-fork
  url: https://gitlab.com/u/jgkamat
- title: terminal
  url: http://onionchesse.wordpress.com/
#  - title: twitter
#   url: http://twitter.com/jekyllrb
#  - title: facebook
#    url:
#    TODO change linux to dockerhub when fa-docker comes out


# Postal address (add as many lines as necessary)
address:
- line: Sunnyvale, CA

    # Build settings
  markdown: kramdown
  permalink: pretty
